twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        var_js: '@App\Service\JsVariable'
        profile_image: '%profile_image%'
        question_response_service: '@App\Service\QuestionResponseService'

when@test:
    twig:
        strict_variables: true
