version: "3"
services:
  database:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kg-dataweb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: khaleddwm/benkod_test_edifitek:v0.1
    ports:
      - "80:80"

volumes:
  db_data: {}
